[package]
name    = "zdu"
version = "0.1.0"
edition = "2024"

[dependencies]

app-error         = { workspace = true }
chrono            = { workspace = true }
clap              = { features = ["derive"], workspace = true }
clap_complete     = { workspace = true }
derive_more       = { features = ["full"], workspace = true }
extend            = { workspace = true }
humansize         = { workspace = true }
itertools         = { workspace = true }
md5               = { workspace = true }
memchr            = { workspace = true }
owo-colors        = { workspace = true }
postcard          = { features = ["use-std"], workspace = true }
serde             = { features = ["derive"], workspace = true }
strum             = { features = ["derive"], workspace = true }
thiserror         = { workspace = true }
tracing           = { workspace = true }
tracing-indicatif = { workspace = true }
zutil-logger      = { workspace = true }

[lints]
workspace = true
